# NodeJS on Ubuntu server

---

- name: Basic setup for a 64bit Ubuntu Server
  hosts: nodejs-ubuntu
  sudo: yes
  #roles:
  #  - basic-setup

- name: Specific setup for the NodeJS PaaS
  hosts: nodejs-ubuntu
  sudo: yes
  vars_files:
    - roles/nodejs-paas/defaults/variables.yml
  roles:
    - nodejs-paas

