# Debian related OSs                                                                                                                                                                                               
---
- name: Apt update
  action: apt update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
